apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-secret-reader
  annotations:
    description: "Intended to grant read-only access to secrets within the database namespace only for the database administrator"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
