apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: search-pod-deleter
  annotations:
    description: "Intended to grant pod delete access within the search namespace only for the search maintenance operator"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
