apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-ingress-manager
  annotations:
    description: "Intended to grant ingress create and update access within the api namespace only for the API routing administrator"
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "patch"]
