apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-serviceaccount-reader
  annotations:
    description: "Intended to grant read-only access to service accounts within the security namespace only for the security audit team"
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch"]
